apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: opsboard-cluster
  region: ap-south-1

iam:
  withOIDC: true

managedNodeGroups:
  - name: opsboard-workers
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    privateNetworking: false
