apiVersion: v2

name: opsboard

description: Production Ready Helm Chart for OpsBoard

type: application

version: 1.0.0

appVersion: "1.0.0"

keywords:
  - devops
  - aws
  - eks
  - kubernetes
  - helm
  - fastapi
  - react

maintainers:
  - name: Ujjwal Agarwal

annotations:
  category: DevOps
