apiVersion: v1
kind: ConfigMap

metadata:
  name: opsboard-backend-config

  namespace: {{ .Values.namespace }}

  labels:
{{ include "opsboard.labels" . | indent 4 }}

data:

  APP_NAME: "OpsBoard API"

  APP_VERSION: "1.0.0"

  ENVIRONMENT: "production"

  DEBUG: "false"

  LOG_LEVEL: "INFO"

  API_PREFIX: "/api"

  CORS_ORIGINS: "*"

  POSTGRES_HOST: "{{ .Values.postgres.host }}"

  POSTGRES_PORT: "{{ .Values.postgres.port }}"

  SEED_DATABASE: "true"
