apiVersion: v1
kind: Service

metadata:

  name: {{ .Values.loadBalancer.serviceName }}

  namespace: {{ .Values.namespace }}

spec:

  type: LoadBalancer

  selector:

    app: {{ .Values.frontend.serviceName }}

  ports:

  - port: {{ .Values.loadBalancer.port }}

    targetPort: {{ .Values.loadBalancer.targetPort }}

    protocol: TCP
