name: Deploy OpsBoard to Amazon EKS

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/opsboard/values.yaml'

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  BACKEND_REPOSITORY: opsboard-backend
  FRONTEND_REPOSITORY: opsboard-frontend

jobs:
  deploy:
    name: Build, Push & Update GitOps
    runs-on: ubuntu-latest

    steps:

      ########################################################
      # Checkout Repository
      ########################################################

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      ########################################################
      # Configure AWS Credentials (OIDC)
      ########################################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      ########################################################
      # Login to Amazon ECR
      ########################################################

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      ########################################################
      # Generate Image Tag
      ########################################################

      - name: Generate Image Tag
        id: vars
        run: |
          echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      ########################################################
      # Build Backend
      ########################################################

      - name: Build Backend Image
        run: |
          docker build \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPOSITORY:${{ steps.vars.outputs.TAG }} \
            ./backend

      - name: Push Backend Image
        run: |
          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPOSITORY:${{ steps.vars.outputs.TAG }}

      ########################################################
      # Build Frontend
      ########################################################

      - name: Build Frontend Image
        run: |
          docker build \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPOSITORY:${{ steps.vars.outputs.TAG }} \
            ./frontend

      - name: Push Frontend Image
        run: |
          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPOSITORY:${{ steps.vars.outputs.TAG }}

      ########################################################
      # Install yq
      ########################################################

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      ########################################################
      # Update Helm values.yaml
      ########################################################

      - name: Update Helm Image Tags
        env:
          TAG: ${{ steps.vars.outputs.TAG }}
        run: |
          yq -i '.images.backend.tag = strenv(TAG)' helm/opsboard/values.yaml
          yq -i '.images.frontend.tag = strenv(TAG)' helm/opsboard/values.yaml

          echo "===== Updated values.yaml ====="
          cat helm/opsboard/values.yaml

      ########################################################
      # Commit Updated values.yaml
      ########################################################

      - name: Commit Updated Helm Values
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add helm/opsboard/values.yaml

          if git diff --cached --quiet; then
            echo "No changes detected."
            exit 0
          fi

          git commit -m "ci: update image tags to ${{ steps.vars.outputs.TAG }}"
          git push origin main
